name: Prettier
on: [push]

jobs: 
    build: 
        name: Prettier
        runs-on: ubuntu-latest
        steps: 
            - uses: actions/checkout@v1
            - uses: bahmutov/npm-install@v1

            - run: npm run format
            - run: git status

            - uses: mikeal/publish-to-github-action@master
              env:  
                GITHUB_TOKEN: ${{ secrets.PRETTIER_SECRET_KEY }}
                BRANCH_NAME: 18-ubeydullah # This will be changed